#!/usr/bin/env bash 

set -eu

AZARGS=()
whitespace="[[:space:]]"
for i in "$@"
do
    if [[ $i =~ $whitespace ]]
    then
        AZARGS+=(\"$i\")
    else
        AZARGS+=($i)
    fi
done

eval "docker run --rm \
    --volume ${PWD}:/root \
    --volume ${HOME}/.azure:/root/.azure \
    -w=/root \
    mcr.microsoft.com/azure-cli \
    az ${AZARGS[@]}"
